apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: runner-ubuntu
  namespace: argocd
spec:
  project: default
  source:
    repoURL:  https://github.com/capafanwi/argocd.git
    targetRevision: HEAD
    path: non-helm/runners
  destination:
    namespace: cgs
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
