apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tiledb
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/capafanwi/cgs-argocd.git
    targetRevision: HEAD
    path: non-helm/eck
    kustomize:
      namePrefix: tiledb-
  destination:
    namespace: cgs   
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
