apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: cgs
  name: pod-manager
rules:
- apiGroups: [""]
  resources: ["pods", "pods/log"]
  verbs: ["get", "list", "watch", "create", "delete"]
- apiGroups: [""]
  resources: ["services", "endpoints"]
  verbs: ["get", "list", "watch", "create", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pod-manager-binding
  namespace: cgs
subjects:
- kind: ServiceAccount
  name: argowf-artifacts-cgs
  namespace: cgs
roleRef:
  kind: Role
  name: pod-manager
  apiGroup: rbac.authorization.k8s.io
